#if !defined(BLE_TASK_H)
#define BLE_TASK_H


/*
 *******************************************************************************
 *                          (C) Copyright 2019 Somnox                          *
 * Created: 30/09/2019                                                         *
 *                                                                             *
 * Programmer(s):                                                              *
 * - Charles Randolph                                                          *
 *                                                                             *
 * Description:                                                                *
 *  Header for the Bluetooth Low Energy Task. This task interfaces with the un *
 *  derlying BLE driver task and allows other tasks to be notified of changes  *
 *  to the connection state. It also is responsible for writing messages to th *
 *  e GATT characteristic and processing messages sent from the connected devi *
 *  ce                                                                         *
 *                                                                             *
 *******************************************************************************
*/


#include "esp_system.h"
#include "esp_log.h"
#include "err.h"
#include "msg.h"
#include "tasks.h"
#include "ipc.h"
#include "ble.h"


/*
 *******************************************************************************
 *                              Global Variables                               *
 *******************************************************************************
*/


/*
 *******************************************************************************
 *                            Function Declarations                            *
 *******************************************************************************
*/


/* Automaton responsible for managing events generated by the BLE driver
 *
*/
void task_ble_manager (void *args);


#endif