#if !defined(BLE_TASK_H)
#define BLE_TASK_H


/*
 *******************************************************************************
 *                          (C) Copyright 2019 Somnox                          *
 * Created: 30/09/2019                                                         *
 *                                                                             *
 * Programmer(s):                                                              *
 * - Charles Randolph                                                          *
 *                                                                             *
 * Description:                                                                *
 *  Header for the Bluetooth Low Energy Task. This task interfaces with the un *
 *  derlying BLE driver task and allows other tasks to be notified of changes  *
 *  to the connection state. It also is responsible for writing messages to th *
 *  e GATT characteristic and processing messages sent from the connected devi *
 *  ce                                                                         *
 *                                                                             *
 *******************************************************************************
*/


#include "esp_system.h"
#include "esp_log.h"
#include "err.h"
#include "msg.h"
#include "tasks.h"
#include "ipc.h"
#include "ble.h"


/*
 *******************************************************************************
 *                              Global Variables                               *
 *******************************************************************************
*/


// Holds the WiFi SSID for all tasks to access (external ref to esp32_wifi_main)
extern uint8_t g_wifi_ssid_buffer[];


// Holds the WiFi PSWD for all tasks to access (external ref to esp32_wifi_main)
extern uint8_t g_wifi_pswd_buffer[];


// Holds the IPv4 address for telemetry (network byte order)
extern uint32_t g_telemetry_inet_addr;


// Holds the port for telemetry data to be sent over (network byte order)
extern uint16_t g_telemetry_inet_port;


// Holds the IPv4 address for the data stream (network byte order)
extern uint32_t g_stream_inet_addr;


// Holds the port for the data stream to be sent over (network byte order)
extern uint16_t g_stream_inet_port;


// Holds the path for the data stream GET request
extern uint8_t g_stream_url_path[64 + 1];


/*
 *******************************************************************************
 *                            Function Declarations                            *
 *******************************************************************************
*/


/* Automaton responsible for managing events generated by the BLE driver
 *
*/
void task_ble_manager (void *args);


#endif