#if !defined(WIFI_TASK_H)
#define WIFI_TASK_H


/*
 *******************************************************************************
 *                          (C) Copyright 2019 Somnox                          *
 * Created: 30/09/2019                                                         *
 *                                                                             *
 * Programmer(s):                                                              *
 * - Charles Randolph                                                          *
 *                                                                             *
 * Description:                                                                *
 *  Header for the WiFi task. This task manages events generated by the backgr *
 *  ound WiFi driver and communicates connectivity information to other tasks  *
 *                                                                             *
 *******************************************************************************
*/


#include <string.h>
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "lwip/err.h"
#include "lwip/sys.h"
#include "err.h"
#include "msg.h"
#include "wifi.h"
#include "tasks.h"
#include "ipc.h"
#include "status.h"


/*
 *******************************************************************************
 *                              Global Variables                               *
 *******************************************************************************
*/


// Holds the WiFi IP address (network byte order) (external ref)
extern uint32_t g_wifi_lan_addr;


// Holds the WiFi SSID for all tasks to access (external ref to esp32_wifi_main)
extern uint8_t g_wifi_ssid_buffer[];


// Holds the WiFi PSWD for all tasks to access (external ref to esp32_wifi_main)
extern uint8_t g_wifi_pswd_buffer[];


// Global state flag (may be subject race conditions | see msg.h for bits)
extern uint8_t g_state_flag;


/*
 *******************************************************************************
 *                            Function Declarations                            *
 *******************************************************************************
*/


/* Automaton responsible for managing events generated by the WiFi driver and
 * LwIP stack. 
*/
void task_wifi_manager (void *args);


#endif